# Site settings
title: Nada Elnaiem
email: elnaiem.nada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nada’s description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nadaelnaiem.github.io" # the base hostname & protocol for your site
twitter_username: nadaaelnaiem
github_username: nadaelnaiem

# Build settings
markdown: kramdown
